spring:
  application:
    name: ApiGateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes[0]:
        id: goods-service
        uri: lb://goods-service
        predicates:
          - Path=/goods/**
      routes[1]:
        id: users-service
        uri: lb://users-service
        predicates:
          - Path=/users/**, /auth/**
eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8011/eureka/
server:
  port: 8012